export const bifastList = [
    { "id_bank": "BTANIDJA", "nama_bank": "Bank Tabungan Negara", "kode": 9 },
    { "id_bank": "BBBAIDJA", "nama_bank": "Bank Permata", "kode": 14 },
    { "id_bank": "BDINIDJA", "nama_bank": "Bank Danamon Indonesia", "kode": 13 },
    { "id_bank": "BNIAIDJA", "nama_bank": "Bank CIMB Niaga", "kode": 18 },
    { "id_bank": "MUABIDJA", "nama_bank": "Bank Muamalat Indonesia", "kode": 19 },
    { "id_bank": "MEGAIDJA", "nama_bank": "Bank Mega", "kode": 17 },
    { "id_bank": "PDKTIDJ1", "nama_bank": "BPD Kaltimtara", "kode": 85 },
    { "id_bank": "DANAIDJ1", "nama_bank": "DANA", "kode": 316 },
    { "id_bank": "PDJTIDJ1", "nama_bank": "BPD Jatim", "kode": 81 },
    { "id_bank": "PDWSIDJA", "nama_bank": "Bank Sulselbar", "kode": 95 },
    { "id_bank": "BSSPIDSP", "nama_bank": "BPD Sumsel Babel", "kode": 48 },
    { "id_bank": "JAGBIDJA", "nama_bank": "Bank Jago", "kode": 214 },
    { "id_bank": "IBBKIDJA", "nama_bank": "Bank Maybank Indonesia", "kode": 60 },
    { "id_bank": "PDJGIDJ1", "nama_bank": "BPD Jateng", "kode": 79 },
    { "id_bank": "NISPIDJA", "nama_bank": "Bank OCBC", "kode": 74 },
    { "id_bank": "BSYAIDJA", "nama_bank": "Bank Central Asia Syariah", "kode": 112 },
    { "id_bank": "PDJBIDJA", "nama_bank": "Bank BJB", "kode": 78 },
    { "id_bank": "PDSUIDJ1", "nama_bank": "BPD Sumut", "kode": 92 },
    { "id_bank": "BNINIDJA", "nama_bank": "Bank Negara Indonesia", "kode": 5 },
    { "id_bank": "BRINIDJA", "nama_bank": "Bank Rakyat Indonesia", "kode": 1 },
    { "id_bank": "CENAIDJA", "nama_bank": "Bank Central Asia", "kode": 2 },
    { "id_bank": "BSMDIDJA", "nama_bank": "Bank Syariah Indonesia", "kode": 11 },
    { "id_bank": "DANAIDJ1", "nama_bank": "DANA", "kode": 316 },
    { "id_bank": "SSPIIDJA", "nama_bank": "Seabank", "kode": 65 }
]